### ISSUE TITLE
关于家长智学网账号无法登录的问题及功能建议

### ISSUE THREAD

**Issue by Terminal-Void** [ArcticLampyrid/zhixue#13]
首先，特别感谢这个软件，在学习中起到很大帮助。谢谢作者。
## 问题
在使用过程中，发现在登录家长账号时，会出现“Cannot read property 'name' undefinded”的问题。学生端一切正常。
学生端账号登录网页智学网：
<img width="630" alt="image" src="https://user-images.githubusercontent.com/60608543/159961149-0aea9674-dca3-4909-91f2-f7bea0515d95.png">
图〇
家长端账号登录网页智学网：
<img width="955" alt="image" src="https://user-images.githubusercontent.com/60608543/159961445-eeb4050e-1cc0-4408-a211-85a8b4a0e219.png">
图一

## 功能建议
建议增加查看班级排名的功能

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/60608543/159962140-7853f577-cf33-483d-87f2-63f6efe9a395.png">
图二

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/60608543/159962679-f838c7da-c3b5-430c-83fe-c1b976f28e6c.png">
图三

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/60608543/159962921-0bafb165-9c4d-4ea8-88db-40792220341a.png">
图四

谢谢🙏

**Comment by ArcticLampyrid** [comment]
> 建议增加查看班级排名的功能

这个貌似不是排名，只是一个大致的等级数据（智学网API里真实的rank基本都删除了）

**Comment by Terminal-Void** [comment]
登录老师账号貌似挺准的【不知道怎么着，一不小心就登上了[手动狗头]】

**Comment by ArcticLampyrid** [comment]
其实有些学校需要年级主任的号才可以看到年级排名

**Comment by Terminal-Void** [comment]
阿这

**Comment by Terminal-Void** [comment]
MacOS找不到对应版本
ps.想当年我做了一个假的登录页面还劫持了老师电脑DNS搞到了账号（违法行为）

**Comment by ArcticLampyrid** [comment]
> ps.想当年我做了一个假的登录页面还劫持了老师电脑DNS搞到了账号（违法行为）

感觉其实扔个油猴脚本就够了吧

**Comment by ArcticLampyrid** [comment]
> MacOS找不到对应版本

建议自行build，手头既没有apple设备也没相关开发者签名

**Comment by Terminal-Void** [comment]
OK

**Comment by Terminal-Void** [comment]
考得怎么样
（夹带私货）

**Comment by ArcticLampyrid** [comment]
高考结束前拒绝回答（毕竟没有可炫耀的点🤕）

**Comment by Terminal-Void** [comment]
我还有几天也中考了。

**Comment by ArcticLampyrid** [comment]
加油啊

**Comment by Terminal-Void** [comment]
加油

**Comment by Terminal-Void** [comment]
补课(违法行为x2)去了。。拜拜

**Comment by Terminal-Void** [comment]
收到提醒邮件死去的记忆突然开始攻击我
